---
- name: Install memcached
  yum:
    name: "{{ memcached_pkg }}"
    state: present

- name: Enable memcached on boot
  service:
    name: memcached
    enabled: yes

- name: Start memcached
  service:
    name: memcached
    state: started

- name: Put in place logrotate configuration
  template:
    src: "logrotate-memcached.j2"
    dest: "/etc/logrotate.d"
    owner: root
    group: root
    mode: 0644